### PR TITLE
Trying to make create_link more robust

### LINKED ISSUE #165: If .local cockpit folder does not exist the script fails loudly
https://github.com/Skaginn3x/framework/blob/729586370b88364130eea8d3510fbc0af5bc4826/cockpit/IPC/install/create_link.js#L6

Maybe create it instead.

### PR DESCRIPTION
**Pull request by SindriTh**
Fixes #165

### CODE REVIEW

File: cockpit/IPC/install/create_link.js [hunk 1]
```diff
@@ -1,26 +1,42 @@
...
-const moduleFolderName = moduleRootDir.substring(moduleRootDir.lastIndexOf('/') + 1, moduleRootDir.length);
+const moduleFolderName = path.basename(moduleRootDir);
 console.log(`Linking ${targetDir} to ${moduleRootDir} as ${moduleFolderName}`);
 
+// Check if symlink already exists
+if (fs.existsSync(moduleFolderName)) {
+    console.log(`A file or directory with the name ${moduleFolderName} already exists in ${targetDir}.`);
+    process.exit(1);
+}
+
```
Comment (omarhogni) [inline cockpit/IPC/install/create_link.js:28]: Does this need to be an error? this is run as part of npm run devbuild and could just be the second time somebody ran devbuild.

Comment (SindriTh) [reply cockpit/IPC/install/create_link.js:28]: Correct, This should exit with 0

**Review by omarhogni — APPROVED** [review]
LGTM
