### PR TITLE
Fixing Filter Modal in Connections view

### LINKED ISSUE #229: View broken of editing filters
image

### PR DESCRIPTION
**Pull request by SindriTh**
fixes #229.

### CODE REVIEW

**Review by jbbjarnason — CHANGES_REQUESTED** [review]
small improvements but not quite there

https://github.com/Skaginn3x/framework/assets/15651464/7cd659d4-6750-4db1-9d42-b3f32467d20d

File: cockpit/IPC/src/Components/Table/FilterModal.tsx [hunk 1]
```diff
@@ -50,6 +55,9 @@ export default function FilterModal({
         setSchema(parsedSchema);
         setFormData(parsedData);
         setIsLoading(false);
+      }).catch((err) => {
+        addAlert(err.message, AlertVariant.danger);
```
Comment (jbbjarnason) [inline cockpit/IPC/src/Components/Table/FilterModal.tsx:59]: nice!

**Review by jbbjarnason — APPROVED** [review]
